-- DROP TABLE HARVEST;
-- DROP TABLE TREE;
-- DROP TABLE TREE_SPECIE;
-- DROP TABLE TREE_GROUP;

CREATE TABLE TREE_SPECIE(
    [ID] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[DESCRIPTION] [varchar](250) NOT NULL
);

CREATE TABLE TREE_GROUP(
    [ID] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    [NAME] [varchar](250) NOT NULL,
	[DESCRIPTION] [varchar](250) NOT NULL
);

CREATE TABLE TREE(
    [ID] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[DESCRIPTION] [varchar](250) NOT NULL,
	[AGE] INT NOT NULL,
    [ID_TREE_SPECIE] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TREE_SPECIE(ID),
    [ID_TREE_GROUP] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TREE_GROUP(ID)
);

CREATE TABLE HARVEST(
    [ID] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[INFORMATION] [varchar](250) NOT NULL,
	[DATE] DATETIME NOT NULL,
    [GROSS_WEIGHT] [decimal](5, 2) NULL,
    ID_TREE UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TREE(ID)
);

